//created on: 6.04.2013
package com.reafs.rules

import com.reafs.input.UserInput;
import com.reafs.input.types.*;
import com.reafs.output.types.*;
import com.reafs.estates.EstateProperty;

rule "When real estate type matches estate propery type"
	when
		estatePropery : EstateProperty( $realEstateType : realEstateType )
		exists RealEstateType(  )
		not RealEstateType( this == $realEstateType )
	then
		estatePropery.setSuitable(false);
end

rule "When plot size matches estate plot size"
	when
		estatePropery : EstateProperty( $plotSize : plotSize )
		exists PlotSize(  )
		not PlotSize( this == $plotSize )
	then
		estatePropery.setSuitable(false);
end

rule "When location matches estate location"
	when
		estatePropery : EstateProperty( $realEstateLocation : realEstateLocation )
		#restriction type exists
		exists RealEstateLocation(  )
		#there is no restriction with the type of estate property
		not RealEstateLocation( this == $realEstateLocation )
	then
		estatePropery.setSuitable(false);
end